import MainNav from "@/components/generic/header/main-nav";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/generic/footer";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Decimal Solutions",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await fetch(
    "https://backend.decimalsolution.com/api/v1/web/contactUs",
    {
      next: {
        revalidate: 300,
      },
    }
  );

  const response = await data.json();
  const contactInfo = response.data[0];

  return (
    <html lang="en">
      <body className={poppins.className}>
        <MainNav contactInfo={contactInfo} />
        {children}
        <Footer contactInfo={contactInfo} />
      </body>
    </html>
  );
}
